name: Auto approve dependabot PRs
on:
  pull_request:
    branches:
      - master

jobs:
  approve-dependabot-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{repo}/pulls/{pull_number}/reviews
          repo: "${{ github.repository }}"
          pull_number: "${{ github.event.number }}"
          event: "APPROVE"
          body: "@dependabot merge"
