
name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}

      - run: |-
          pnpm install --frozen-lockfile
          pnpm build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
